### ISSUE TITLE
Error running SAC+FILM and CARE, Configuration file seems missing

### ISSUE THREAD

**Issue by NagisaZj** [facebookresearch/mtrl#25]
# Description

I am trying to run SAC+FILM and CARE according to the commands in the documentation, but it seems configuration files are missing.

## How to reproduce

Run the SAC+FILM and CARE commands according to the documentation:
```
#film
CUDA_VISIBLE_DEVICES=4 OPENBLAS_NUM_THREADS=4 PYTHONPATH=. python3 -u main.py \
setup=metaworld \
env=metaworld-mt10 \
agent=state_sac \
experiment.num_eval_episodes=1 \
experiment.num_train_steps=2000000 \
setup.seed=4 \
replay_buffer.batch_size=1280 \
agent.multitask.num_envs=10 \
agent.multitask.should_use_disentangled_alpha=True \
agent.multitask.should_use_task_encoder=True \
agent.encoder.type_to_select=film \
agent.multitask.should_use_multi_head_policy=False \
agent.multitask.task_encoder_cfg.model_cfg.pretrained_embedding_cfg.should_use=True \
agent.multitask.task_encoder_cfg.model_cfg.output_dim=6

#care
CUDA_VISIBLE_DEVICES=5 OPENBLAS_NUM_THREADS=4 PYTHONPATH=. python3 -u main.py \
setup=metaworld \
env=metaworld-mt10 \
agent=state_sac \
experiment.num_eval_episodes=1 \
experiment.num_train_steps=2000000 \
setup.seed=5 \
replay_buffer.batch_size=1280 \
agent.multitask.num_envs=10 \
agent.multitask.should_use_disentangled_alpha=True \
agent.multitask.should_use_task_encoder=True \
agent.encoder.type_to_select=moe \
agent.multitask.should_use_multi_head_policy=False \
agent.encoder.moe.task_id_to_encoder_id_cfg.mode=attention \
agent.encoder.moe.num_experts=4 \
agent.multitask.task_encoder_cfg.model_cfg.pretrained_embedding_cfg.should_use=True
```

**Stack trace / error message**
For SAC+FILM:
```
Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 500, in _instantiate_class
    return clazz(*args, **final_kwargs)
  File "/data3/zj/mtrl/mtrl/agent/components/task_encoder.py", line 39, in __init__
    with open(pretrained_embedding_cfg.path_to_load_from) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 500, in _instantiate_class
    return clazz(*args, **final_kwargs)
  File "/data3/zj/mtrl/mtrl/agent/sac.py", line 116, in __init__
    self.multitask_cfg.task_encoder_cfg.model_cfg,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.agent.components.task_encoder.TaskEncoder' : [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 500, in _instantiate_class
    return clazz(*args, **final_kwargs)
  File "/data3/zj/mtrl/mtrl/experiment/metaworld.py", line 20, in __init__
    super().__init__(config, experiment_id)
  File "/data3/zj/mtrl/mtrl/experiment/multitask.py", line 25, in __init__
    super().__init__(config, experiment_id)
  File "/data3/zj/mtrl/mtrl/experiment/experiment.py", line 72, in __init__
    device=self.device,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.agent.sac.Agent' : Error calling 'mtrl.agent.components.task_encoder.TaskEncoder' : [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 15, in launch
    return run(config)
  File "/data3/zj/mtrl/mtrl/app/run.py", line 35, in run
    experiment_utils.prepare_and_run(config=config)
  File "/data3/zj/mtrl/mtrl/experiment/utils.py", line 24, in prepare_and_run
    config.experiment.builder, config
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.experiment.metaworld.Experiment' : Error calling 'mtrl.agent.sac.Agent' : Error calling 'mtrl.agent.components.task_encoder.TaskEncoder' : [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    launch()
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 237, in run_and_report
    assert mdl is not None
AssertionError

```

For CARE:

```
Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 500, in _instantiate_class
    return clazz(*args, **final_kwargs)
  File "/data3/zj/mtrl/mtrl/agent/components/task_encoder.py", line 39, in __init__
    with open(pretrained_embedding_cfg.path_to_load_from) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 500, in _instantiate_class
    return clazz(*args, **final_kwargs)
  File "/data3/zj/mtrl/mtrl/agent/sac.py", line 116, in __init__
    self.multitask_cfg.task_encoder_cfg.model_cfg,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.agent.components.task_encoder.TaskEncoder' : [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 63, in call
    return _instantiate_class(type_or_callable, config, *args, **kwargs)
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 500, in _instantiate_class
    return clazz(*args, **final_kwargs)
  File "/data3/zj/mtrl/mtrl/experiment/metaworld.py", line 20, in __init__
    super().__init__(config, experiment_id)
  File "/data3/zj/mtrl/mtrl/experiment/multitask.py", line 25, in __init__
    super().__init__(config, experiment_id)
  File "/data3/zj/mtrl/mtrl/experiment/experiment.py", line 72, in __init__
    device=self.device,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.agent.sac.Agent' : Error calling 'mtrl.agent.components.task_encoder.TaskEncoder' : [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 15, in launch
    return run(config)
  File "/data3/zj/mtrl/mtrl/app/run.py", line 35, in run
    experiment_utils.prepare_and_run(config=config)
  File "/data3/zj/mtrl/mtrl/experiment/utils.py", line 24, in prepare_and_run
    config.experiment.builder, config
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'mtrl.experiment.metaworld.Experiment' : Error calling 'mtrl.agent.sac.Agent' : Error calling 'mtrl.agent.components.task_encoder.TaskEncoder' : [Errno 2] No such file or directory: '/private/home/sodhani/projects/mtrl/metadata/task_embedding/roberta_small/metaworld-mt10.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    launch()
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/zj/anaconda3/envs/context/lib/python3.6/site-packages/hydra/_internal/utils.py", line 237, in run_and_report
    assert mdl is not None
AssertionError

```

## System information
- **MTRL Version** :  [Latest commit on github](https://github.com/facebookresearch/mtrl) (e282c3f5a205970b4ad7d1c1ebae7aa9b4d56218)
- **MTRL environment Name** :  context
- **Python version** : 3.6.13

## Any other information

Add any other information here.

**Comment by NagisaZj** [comment]
Fixed by changing the path in config/agent/components/metaworld_multitask.yaml to my local path.
